// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMqU2q-_C5r3Sqqw7eZLGu5Dq9Sfaw6iY',
    appId: '1:604616938475:web:8d3c7a3377db9f70bc7fae',
    messagingSenderId: '604616938475',
    projectId: 'mayurance-ac-services',
    authDomain: 'mayurance-ac-services.firebaseapp.com',
    storageBucket: 'mayurance-ac-services.appspot.com',
    measurementId: 'G-5PWLNXTGH0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6CoHrJ1QsZJF7krOG8jeeml0qBV46-Oo',
    appId: '1:604616938475:android:d35180a192c2b16dbc7fae',
    messagingSenderId: '604616938475',
    projectId: 'mayurance-ac-services',
    storageBucket: 'mayurance-ac-services.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSmDKpOIBZYiHYTwA6eeDDJ30ecr0bnik',
    appId: '1:604616938475:ios:25aa8da7a4466ab6bc7fae',
    messagingSenderId: '604616938475',
    projectId: 'mayurance-ac-services',
    storageBucket: 'mayurance-ac-services.appspot.com',
    iosBundleId: 'com.example.mayurance',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSmDKpOIBZYiHYTwA6eeDDJ30ecr0bnik',
    appId: '1:604616938475:ios:f2996db39afc6213bc7fae',
    messagingSenderId: '604616938475',
    projectId: 'mayurance-ac-services',
    storageBucket: 'mayurance-ac-services.appspot.com',
    iosBundleId: 'com.example.mayurance.RunnerTests',
  );
}
